# Staging environment configuration
replicaCount: 2
image:
  repository: docker.io/gajjarvatsall/multi-env-cicd
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30081

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  NODE_ENV: staging
  APP_VERSION: "1.0.0"