# Production environment configuration
replicaCount: 3
image:
  repository: docker.io/gajjarvatsall/multi-env-cicd
  tag: "latest"
  pullPolicy: IfNotPresent

environment: production
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
service:
  type: NodePort
  port: 80
  nodePort: 30082