# Production environment configuration
replicaCount: 3
image:
  repository: docker.io/gajjarvatsall/multi-env-cicd
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30082

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  NODE_ENV: production
  APP_VERSION: "1.0.0"