# Default values for my-app
replicaCount: 1

image:
  repository: docker.io/gajjarvatsall/multi-env-cicd
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

env:
  NODE_ENV: production
  APP_VERSION: "1.0.0"