# Dev environment configuration
replicaCount: 1
image: docker.io/gajjarvatsall/my-app-cicd:latest
environment: development
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
service:
  type: NodePort
  port: 80
  nodePort: 30080