# Dev environment configuration
replicaCount: 1
image:
  repository: docker.io/gajjarvatsall/multi-env-cicd
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  NODE_ENV: development
  APP_VERSION: "1.0.0"